on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
        name: Checkout the repository
      - uses: ./
        name: Hello world action step
        id: hello
        with:
          who-to-greet: "Kashif Ghafoor"
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
